"""Payload helpers for HTTP Data Bridge."""

from __future__ import annotations

from collections.abc import Iterator
import json
import math
import re
from typing import Any

from homeassistant.const import MAX_LENGTH_STATE_STATE

from .const import (
    FIELD_PLATFORM,
    FIELD_STORE_IN_ATTRIBUTE,
    FIELD_UNIT,
    PLATFORM_BINARY_SENSOR,
    PLATFORM_SENSOR,
)

JsonValue = None | bool | int | float | str | list["JsonValue"] | dict[str, "JsonValue"]

_CANONICAL_ARRAY_INDEX = re.compile(r"0|[1-9][0-9]*")
_MAX_JSON_DEPTH = 128


def _reject_json_constant(value: str) -> None:
    """Reject non-standard JSON constants such as NaN and Infinity."""
    raise ValueError(value)


def _parse_finite_float(value: str) -> float:
    """Parse a JSON float without allowing Python overflow to infinity."""
    parsed = float(value)
    if not math.isfinite(parsed):
        raise ValueError(value)
    return parsed


def _validate_json_depth(value: JsonValue) -> None:
    """Reject pathologically deep JSON without recursive Python traversal."""
    stack: list[tuple[JsonValue, int]] = [(value, 0)]

    while stack:
        current, depth = stack.pop()
        if depth > _MAX_JSON_DEPTH:
            raise ValueError("JSON nesting is too deep")

        if isinstance(current, dict):
            stack.extend((child, depth + 1) for child in current.values())
        elif isinstance(current, list):
            stack.extend((child, depth + 1) for child in current)


def parse_json(raw: str) -> JsonValue:
    """Parse strict JSON into the scalar/container types supported by the bridge."""
    parsed: JsonValue = json.loads(
        raw,
        parse_constant=_reject_json_constant,
        parse_float=_parse_finite_float,
    )
    _validate_json_depth(parsed)
    return parsed


def _escape_pointer_part(part: str) -> str:
    """Escape one JSON Pointer segment."""
    return part.replace("~", "~0").replace("/", "~1")


def _unescape_pointer_part(part: str) -> str:
    """Unescape one JSON Pointer segment."""
    return part.replace("~1", "/").replace("~0", "~")


def iter_json_nodes(value: JsonValue, pointer: str = "") -> Iterator[tuple[str, JsonValue]]:
    """Yield every JSON node, including root and containers, without recursion."""
    stack: list[tuple[str, JsonValue]] = [(pointer, value)]

    while stack:
        current_pointer, current = stack.pop()
        yield current_pointer, current

        if isinstance(current, dict):
            # Reverse before pushing so iteration order remains the same as the
            # original JSON object when values are popped from the stack.
            for key, child in reversed(list(current.items())):
                child_pointer = (
                    f"{current_pointer}/{_escape_pointer_part(str(key))}"
                )
                stack.append((child_pointer, child))
        elif isinstance(current, list):
            for index in range(len(current) - 1, -1, -1):
                child_pointer = f"{current_pointer}/{index}"
                stack.append((child_pointer, current[index]))


def iter_scalar_fields(value: JsonValue, pointer: str = "") -> Iterator[tuple[str, JsonValue]]:
    """Yield JSON Pointer paths for scalar leaf values without recursive traversal."""
    for current_pointer, current in iter_json_nodes(value, pointer):
        if not isinstance(current, (dict, list)):
            yield current_pointer, current


def get_by_pointer(value: JsonValue, pointer: str) -> JsonValue:
    """Read a value using RFC 6901-style JSON Pointer syntax."""
    if pointer == "":
        return value
    if not pointer.startswith("/"):
        raise KeyError(pointer)

    current: Any = value
    for raw_part in pointer[1:].split("/"):
        part = _unescape_pointer_part(raw_part)
        if isinstance(current, dict):
            current = current[part]
            continue
        if isinstance(current, list):
            # Array references generated by this integration are canonical,
            # non-negative decimal indexes. Reject Python-style negative indexes
            # and leading-zero aliases so an upstream object-to-array shape change
            # cannot silently redirect an existing mapping to a different element.
            if _CANONICAL_ARRAY_INDEX.fullmatch(part) is None:
                raise KeyError(pointer)
            try:
                current = current[int(part)]
            except IndexError as err:
                raise KeyError(pointer) from err
            continue
        raise KeyError(pointer)

    return current


def pointer_to_label(pointer: str) -> str:
    """Convert a JSON Pointer into a readable dotted/indexed path."""
    if pointer == "":
        return "$"

    parts = [_unescape_pointer_part(part) for part in pointer[1:].split("/")]
    label = ""
    for part in parts:
        if part.isdigit():
            label += f"[{part}]"
        else:
            label = f"{label}.{part}" if label else part
    return label


def suggested_name(pointer: str) -> str:
    """Create a human-friendly default name from a pointer."""
    label = pointer_to_label(pointer)
    if label == "$":
        return "Payload"
    leaf = label.rsplit(".", 1)[-1]
    if "[" in leaf and leaf.endswith("]"):
        leaf = leaf.split("[", 1)[0] or "Value"
    return leaf.replace("_", " ").replace("-", " ").strip().title() or "Value"


def sample_display(value: JsonValue, *, limit: int = 80) -> str:
    """Return a compact representation suitable for selector labels."""
    if value is None:
        text = "null"
    elif isinstance(value, bool):
        text = "true" if value else "false"
    elif isinstance(value, dict):
        count = len(value)
        text = f"object ({count} key{'s' if count != 1 else ''})"
    elif isinstance(value, list):
        count = len(value)
        text = f"array ({count} item{'s' if count != 1 else ''})"
    else:
        text = str(value)

    if len(text) > limit:
        return f"{text[: limit - 1]}…"
    return text


def normalise_sensor_value(value: JsonValue) -> str | int | float | None:
    """Normalise a JSON scalar for a SensorEntity."""
    if value is None:
        return None
    if isinstance(value, bool):
        return "on" if value else "off"
    if isinstance(value, (str, int, float)):
        return value
    return None


def mapping_value_is_available(field: dict[str, Any], value: JsonValue) -> bool:
    """Return whether a mapped JSON value can be represented by its HA entity."""
    platform = str(field.get(FIELD_PLATFORM, ""))

    if platform == PLATFORM_BINARY_SENSOR:
        return isinstance(value, bool)

    if platform != PLATFORM_SENSOR:
        return False

    if bool(field.get(FIELD_STORE_IN_ATTRIBUTE, False)):
        return True

    if isinstance(value, (dict, list)):
        return False

    if field.get(FIELD_UNIT) and not (
        isinstance(value, (int, float)) and not isinstance(value, bool)
    ):
        return False

    normalised = normalise_sensor_value(value)
    return normalised is None or len(str(normalised)) <= MAX_LENGTH_STATE_STATE
